/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Me.Client.Client;
using EdGraph.Me.Client.Api;
// uncomment below to import models
//using EdGraph.Me.Client.Model;

namespace EdGraph.Me.Client.Test.Api
{
    /// <summary>
    ///  Class for testing MyExtensionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MyExtensionsApiTests : IDisposable
    {
        private MyExtensionsApi instance;

        public MyExtensionsApiTests()
        {
            instance = new MyExtensionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MyExtensionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MyExtensionsApi
            //Assert.IsType<MyExtensionsApi>(instance);
        }

        /// <summary>
        /// Test RemoveUserExtension
        /// </summary>
        [Fact]
        public void RemoveUserExtensionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string code = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.RemoveUserExtension(code, apiVersion, xVersion);
            //Assert.IsType<IdentityApiUserV1UserExtensionRemovedResponse>(response);
        }

        /// <summary>
        /// Test SetUserExtension
        /// </summary>
        [Fact]
        public void SetUserExtensionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? apiVersion = null;
            //string? xVersion = null;
            //IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = null;
            //var response = instance.SetUserExtension(apiVersion, xVersion, identityApiUserV1SetUserExtensionRequest);
            //Assert.IsType<IdentityApiUserV1UserExtensionSetResponse>(response);
        }
    }
}
