/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Me.Client.Client;
using EdGraph.Me.Client.Api;
// uncomment below to import models
//using EdGraph.Me.Client.Model;

namespace EdGraph.Me.Client.Test.Api
{
    /// <summary>
    ///  Class for testing MyPreferencesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MyPreferencesApiTests : IDisposable
    {
        private MyPreferencesApi instance;

        public MyPreferencesApiTests()
        {
            instance = new MyPreferencesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MyPreferencesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MyPreferencesApi
            //Assert.IsType<MyPreferencesApi>(instance);
        }

        /// <summary>
        /// Test UpdateUserPreferenceAsync
        /// </summary>
        [Fact]
        public void UpdateUserPreferenceAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? apiVersion = null;
            //string? xVersion = null;
            //EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsUpdateUserPreferenceRequest? edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsUpdateUserPreferenceRequest = null;
            //var response = instance.UpdateUserPreferenceAsync(apiVersion, xVersion, edGraphHttpAggregatorsTenantApiControllersV1ViewModelsRequestsUpdateUserPreferenceRequest);
            //Assert.IsType<IdentityApiUserV1UserPreferenceUpdatedResponse>(response);
        }
    }
}
