/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Me.Client.Client;
using EdGraph.Me.Client.Api;
// uncomment below to import models
//using EdGraph.Me.Client.Model;

namespace EdGraph.Me.Client.Test.Api
{
    /// <summary>
    ///  Class for testing MyProfileApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MyProfileApiTests : IDisposable
    {
        private MyProfileApi instance;

        public MyProfileApiTests()
        {
            instance = new MyProfileApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MyProfileApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MyProfileApi
            //Assert.IsType<MyProfileApi>(instance);
        }

        /// <summary>
        /// Test GetUserCacheAsync
        /// </summary>
        [Fact]
        public void GetUserCacheAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetUserCacheAsync(apiVersion, xVersion);
            //Assert.IsType<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse>(response);
        }
    }
}
