/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Me.Client.Client;
using EdGraph.Me.Client.Api;
// uncomment below to import models
//using EdGraph.Me.Client.Model;

namespace EdGraph.Me.Client.Test.Api
{
    /// <summary>
    ///  Class for testing UserProfileApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UserProfileApiTests : IDisposable
    {
        private UserProfileApi instance;

        public UserProfileApiTests()
        {
            instance = new UserProfileApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserProfileApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UserProfileApi
            //Assert.IsType<UserProfileApi>(instance);
        }

        /// <summary>
        /// Test GetUserCache
        /// </summary>
        [Fact]
        public void GetUserCacheTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetUserCache(apiVersion, xVersion);
            //Assert.IsType<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesUserCacheResponse>(response);
        }
    }
}
