/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using EdGraph.Me.Client.Client;
using EdGraph.Me.Client.Client.Auth;
using EdGraph.Me.Client.Model;

namespace EdGraph.Me.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMyExtensionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Removes a user&#39;s profile extension.
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdentityApiUserV1UserExtensionRemovedResponse</returns>
        IdentityApiUserV1UserExtensionRemovedResponse RemoveUserExtension(string code, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);

        /// <summary>
        /// Removes a user&#39;s profile extension.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdentityApiUserV1UserExtensionRemovedResponse</returns>
        ApiResponse<IdentityApiUserV1UserExtensionRemovedResponse> RemoveUserExtensionWithHttpInfo(string code, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);
        /// <summary>
        /// Creates or update a user&#39;s profile extension.
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="identityApiUserV1SetUserExtensionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdentityApiUserV1UserExtensionSetResponse</returns>
        IdentityApiUserV1UserExtensionSetResponse SetUserExtension(string? apiVersion = default(string?), string? xVersion = default(string?), IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = default(IdentityApiUserV1SetUserExtensionRequest?), int operationIndex = 0);

        /// <summary>
        /// Creates or update a user&#39;s profile extension.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="identityApiUserV1SetUserExtensionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdentityApiUserV1UserExtensionSetResponse</returns>
        ApiResponse<IdentityApiUserV1UserExtensionSetResponse> SetUserExtensionWithHttpInfo(string? apiVersion = default(string?), string? xVersion = default(string?), IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = default(IdentityApiUserV1SetUserExtensionRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMyExtensionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Removes a user&#39;s profile extension.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdentityApiUserV1UserExtensionRemovedResponse</returns>
        System.Threading.Tasks.Task<IdentityApiUserV1UserExtensionRemovedResponse> RemoveUserExtensionAsync(string code, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Removes a user&#39;s profile extension.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdentityApiUserV1UserExtensionRemovedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<IdentityApiUserV1UserExtensionRemovedResponse>> RemoveUserExtensionWithHttpInfoAsync(string code, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Creates or update a user&#39;s profile extension.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="identityApiUserV1SetUserExtensionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdentityApiUserV1UserExtensionSetResponse</returns>
        System.Threading.Tasks.Task<IdentityApiUserV1UserExtensionSetResponse> SetUserExtensionAsync(string? apiVersion = default(string?), string? xVersion = default(string?), IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = default(IdentityApiUserV1SetUserExtensionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Creates or update a user&#39;s profile extension.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="identityApiUserV1SetUserExtensionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdentityApiUserV1UserExtensionSetResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<IdentityApiUserV1UserExtensionSetResponse>> SetUserExtensionWithHttpInfoAsync(string? apiVersion = default(string?), string? xVersion = default(string?), IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = default(IdentityApiUserV1SetUserExtensionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMyExtensionsApi : IMyExtensionsApiSync, IMyExtensionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MyExtensionsApi : IMyExtensionsApi
    {
        private EdGraph.Me.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MyExtensionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MyExtensionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyExtensionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MyExtensionsApi(string basePath)
        {
            this.Configuration = EdGraph.Me.Client.Client.Configuration.MergeConfigurations(
                EdGraph.Me.Client.Client.GlobalConfiguration.Instance,
                new EdGraph.Me.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new EdGraph.Me.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EdGraph.Me.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = EdGraph.Me.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyExtensionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MyExtensionsApi(EdGraph.Me.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = EdGraph.Me.Client.Client.Configuration.MergeConfigurations(
                EdGraph.Me.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new EdGraph.Me.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EdGraph.Me.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = EdGraph.Me.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyExtensionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MyExtensionsApi(EdGraph.Me.Client.Client.ISynchronousClient client, EdGraph.Me.Client.Client.IAsynchronousClient asyncClient, EdGraph.Me.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = EdGraph.Me.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public EdGraph.Me.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public EdGraph.Me.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public EdGraph.Me.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public EdGraph.Me.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Removes a user&#39;s profile extension. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdentityApiUserV1UserExtensionRemovedResponse</returns>
        public IdentityApiUserV1UserExtensionRemovedResponse RemoveUserExtension(string code, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserExtensionRemovedResponse> localVarResponse = RemoveUserExtensionWithHttpInfo(code, apiVersion, xVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Removes a user&#39;s profile extension. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdentityApiUserV1UserExtensionRemovedResponse</returns>
        public EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserExtensionRemovedResponse> RemoveUserExtensionWithHttpInfo(string code, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new EdGraph.Me.Client.Client.ApiException(400, "Missing required parameter 'code' when calling MyExtensionsApi->RemoveUserExtension");
            }

            EdGraph.Me.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Me.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", EdGraph.Me.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Me.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "MyExtensionsApi.RemoveUserExtension";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<IdentityApiUserV1UserExtensionRemovedResponse>("/me/extensions/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveUserExtension", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Removes a user&#39;s profile extension. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdentityApiUserV1UserExtensionRemovedResponse</returns>
        public async System.Threading.Tasks.Task<IdentityApiUserV1UserExtensionRemovedResponse> RemoveUserExtensionAsync(string code, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserExtensionRemovedResponse> localVarResponse = await RemoveUserExtensionWithHttpInfoAsync(code, apiVersion, xVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Removes a user&#39;s profile extension. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdentityApiUserV1UserExtensionRemovedResponse)</returns>
        public async System.Threading.Tasks.Task<EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserExtensionRemovedResponse>> RemoveUserExtensionWithHttpInfoAsync(string code, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new EdGraph.Me.Client.Client.ApiException(400, "Missing required parameter 'code' when calling MyExtensionsApi->RemoveUserExtension");
            }


            EdGraph.Me.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Me.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", EdGraph.Me.Client.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Me.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "MyExtensionsApi.RemoveUserExtension";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<IdentityApiUserV1UserExtensionRemovedResponse>("/me/extensions/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RemoveUserExtension", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creates or update a user&#39;s profile extension. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="identityApiUserV1SetUserExtensionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdentityApiUserV1UserExtensionSetResponse</returns>
        public IdentityApiUserV1UserExtensionSetResponse SetUserExtension(string? apiVersion = default(string?), string? xVersion = default(string?), IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = default(IdentityApiUserV1SetUserExtensionRequest?), int operationIndex = 0)
        {
            EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserExtensionSetResponse> localVarResponse = SetUserExtensionWithHttpInfo(apiVersion, xVersion, identityApiUserV1SetUserExtensionRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates or update a user&#39;s profile extension. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="identityApiUserV1SetUserExtensionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdentityApiUserV1UserExtensionSetResponse</returns>
        public EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserExtensionSetResponse> SetUserExtensionWithHttpInfo(string? apiVersion = default(string?), string? xVersion = default(string?), IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = default(IdentityApiUserV1SetUserExtensionRequest?), int operationIndex = 0)
        {
            EdGraph.Me.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Me.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Me.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }
            localVarRequestOptions.Data = identityApiUserV1SetUserExtensionRequest;

            localVarRequestOptions.Operation = "MyExtensionsApi.SetUserExtension";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<IdentityApiUserV1UserExtensionSetResponse>("/me/extensions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetUserExtension", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creates or update a user&#39;s profile extension. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="identityApiUserV1SetUserExtensionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdentityApiUserV1UserExtensionSetResponse</returns>
        public async System.Threading.Tasks.Task<IdentityApiUserV1UserExtensionSetResponse> SetUserExtensionAsync(string? apiVersion = default(string?), string? xVersion = default(string?), IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = default(IdentityApiUserV1SetUserExtensionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserExtensionSetResponse> localVarResponse = await SetUserExtensionWithHttpInfoAsync(apiVersion, xVersion, identityApiUserV1SetUserExtensionRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates or update a user&#39;s profile extension. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="identityApiUserV1SetUserExtensionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdentityApiUserV1UserExtensionSetResponse)</returns>
        public async System.Threading.Tasks.Task<EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserExtensionSetResponse>> SetUserExtensionWithHttpInfoAsync(string? apiVersion = default(string?), string? xVersion = default(string?), IdentityApiUserV1SetUserExtensionRequest? identityApiUserV1SetUserExtensionRequest = default(IdentityApiUserV1SetUserExtensionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            EdGraph.Me.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Me.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Me.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }
            localVarRequestOptions.Data = identityApiUserV1SetUserExtensionRequest;

            localVarRequestOptions.Operation = "MyExtensionsApi.SetUserExtension";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<IdentityApiUserV1UserExtensionSetResponse>("/me/extensions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SetUserExtension", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
