/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using EdGraph.Me.Client.Client;
using EdGraph.Me.Client.Client.Auth;
using EdGraph.Me.Client.Model;

namespace EdGraph.Me.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMyTenantsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieves the Tenants of the User that is currently logged in.
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel</returns>
        IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel GetUserTenants(int? pageIndex = default(int?), int? pageSize = default(int?), string? filter = default(string?), string? orderBy = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);

        /// <summary>
        /// Retrieves the Tenants of the User that is currently logged in.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel</returns>
        ApiResponse<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel> GetUserTenantsWithHttpInfo(int? pageIndex = default(int?), int? pageSize = default(int?), string? filter = default(string?), string? orderBy = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMyTenantsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves the Tenants of the User that is currently logged in.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel</returns>
        System.Threading.Tasks.Task<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel> GetUserTenantsAsync(int? pageIndex = default(int?), int? pageSize = default(int?), string? filter = default(string?), string? orderBy = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Retrieves the Tenants of the User that is currently logged in.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel>> GetUserTenantsWithHttpInfoAsync(int? pageIndex = default(int?), int? pageSize = default(int?), string? filter = default(string?), string? orderBy = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMyTenantsApi : IMyTenantsApiSync, IMyTenantsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MyTenantsApi : IMyTenantsApi
    {
        private EdGraph.Me.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MyTenantsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MyTenantsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyTenantsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MyTenantsApi(string basePath)
        {
            this.Configuration = EdGraph.Me.Client.Client.Configuration.MergeConfigurations(
                EdGraph.Me.Client.Client.GlobalConfiguration.Instance,
                new EdGraph.Me.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new EdGraph.Me.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EdGraph.Me.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = EdGraph.Me.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyTenantsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MyTenantsApi(EdGraph.Me.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = EdGraph.Me.Client.Client.Configuration.MergeConfigurations(
                EdGraph.Me.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new EdGraph.Me.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EdGraph.Me.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = EdGraph.Me.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MyTenantsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MyTenantsApi(EdGraph.Me.Client.Client.ISynchronousClient client, EdGraph.Me.Client.Client.IAsynchronousClient asyncClient, EdGraph.Me.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = EdGraph.Me.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public EdGraph.Me.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public EdGraph.Me.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public EdGraph.Me.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public EdGraph.Me.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieves the Tenants of the User that is currently logged in. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel</returns>
        public IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel GetUserTenants(int? pageIndex = default(int?), int? pageSize = default(int?), string? filter = default(string?), string? orderBy = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel> localVarResponse = GetUserTenantsWithHttpInfo(pageIndex, pageSize, filter, orderBy, apiVersion, xVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves the Tenants of the User that is currently logged in. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel</returns>
        public EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel> GetUserTenantsWithHttpInfo(int? pageIndex = default(int?), int? pageSize = default(int?), string? filter = default(string?), string? orderBy = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            EdGraph.Me.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Me.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Me.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "MyTenantsApi.GetUserTenants";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel>("/me/tenants", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserTenants", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves the Tenants of the User that is currently logged in. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel</returns>
        public async System.Threading.Tasks.Task<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel> GetUserTenantsAsync(int? pageIndex = default(int?), int? pageSize = default(int?), string? filter = default(string?), string? orderBy = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel> localVarResponse = await GetUserTenantsWithHttpInfoAsync(pageIndex, pageSize, filter, orderBy, apiVersion, xVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves the Tenants of the User that is currently logged in. 
        /// </summary>
        /// <exception cref="EdGraph.Me.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel)</returns>
        public async System.Threading.Tasks.Task<EdGraph.Me.Client.Client.ApiResponse<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel>> GetUserTenantsWithHttpInfoAsync(int? pageIndex = default(int?), int? pageSize = default(int?), string? filter = default(string?), string? orderBy = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            EdGraph.Me.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Me.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Me.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Me.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Me.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "MyTenantsApi.GetUserTenants";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel>("/me/tenants", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserTenants", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
