/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1TenantType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1TenantTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1TenantType
        //private IdentityApiUserV1TenantType instance;

        public IdentityApiUserV1TenantTypeTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1TenantType
            //instance = new IdentityApiUserV1TenantType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1TenantType
        /// </summary>
        [Fact]
        public void IdentityApiUserV1TenantTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1TenantType
            //Assert.IsType<IdentityApiUserV1TenantType>(instance);
        }
    }
}
