/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UpdateUserPreferenceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UpdateUserPreferenceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UpdateUserPreferenceRequest
        //private IdentityApiUserV1UpdateUserPreferenceRequest instance;

        public IdentityApiUserV1UpdateUserPreferenceRequestTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UpdateUserPreferenceRequest
            //instance = new IdentityApiUserV1UpdateUserPreferenceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UpdateUserPreferenceRequest
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UpdateUserPreferenceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UpdateUserPreferenceRequest
            //Assert.IsType<IdentityApiUserV1UpdateUserPreferenceRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ClaimName'
        /// </summary>
        [Fact]
        public void ClaimNameTest()
        {
            // TODO unit test for the property 'ClaimName'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
