/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfile
        //private IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfile instance;

        public IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfileTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfile
            //instance = new IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfile
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfile
            //Assert.IsType<IdentityApiUserV1UserTenantProfileTypesUserTenantEducationOrganizationProfile>(instance);
        }

        /// <summary>
        /// Test the property 'EducationOrganizationId'
        /// </summary>
        [Fact]
        public void EducationOrganizationIdTest()
        {
            // TODO unit test for the property 'EducationOrganizationId'
        }

        /// <summary>
        /// Test the property 'ShortNameOfInstitution'
        /// </summary>
        [Fact]
        public void ShortNameOfInstitutionTest()
        {
            // TODO unit test for the property 'ShortNameOfInstitution'
        }

        /// <summary>
        /// Test the property 'NameOfInstitution'
        /// </summary>
        [Fact]
        public void NameOfInstitutionTest()
        {
            // TODO unit test for the property 'NameOfInstitution'
        }

        /// <summary>
        /// Test the property 'StaffClassifications'
        /// </summary>
        [Fact]
        public void StaffClassificationsTest()
        {
            // TODO unit test for the property 'StaffClassifications'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
    }
}
