/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfile
        //private IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfile instance;

        public IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfileTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfile
            //instance = new IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfile
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfile
            //Assert.IsType<IdentityApiUserV1UserTenantProfileTypesUserTenantLicenseProfile>(instance);
        }

        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }

        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Fact]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
    }
}
