/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UserTenantProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UserTenantProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UserTenantProfile
        //private IdentityApiUserV1UserTenantProfile instance;

        public IdentityApiUserV1UserTenantProfileTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UserTenantProfile
            //instance = new IdentityApiUserV1UserTenantProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UserTenantProfile
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UserTenantProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UserTenantProfile
            //Assert.IsType<IdentityApiUserV1UserTenantProfile>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'TenantType'
        /// </summary>
        [Fact]
        public void TenantTypeTest()
        {
            // TODO unit test for the property 'TenantType'
        }

        /// <summary>
        /// Test the property 'TenantStatus'
        /// </summary>
        [Fact]
        public void TenantStatusTest()
        {
            // TODO unit test for the property 'TenantStatus'
        }

        /// <summary>
        /// Test the property 'OrganizationIdentifier'
        /// </summary>
        [Fact]
        public void OrganizationIdentifierTest()
        {
            // TODO unit test for the property 'OrganizationIdentifier'
        }

        /// <summary>
        /// Test the property 'OrganizationName'
        /// </summary>
        [Fact]
        public void OrganizationNameTest()
        {
            // TODO unit test for the property 'OrganizationName'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'IsDemo'
        /// </summary>
        [Fact]
        public void IsDemoTest()
        {
            // TODO unit test for the property 'IsDemo'
        }

        /// <summary>
        /// Test the property 'EducationOrganizations'
        /// </summary>
        [Fact]
        public void EducationOrganizationsTest()
        {
            // TODO unit test for the property 'EducationOrganizations'
        }

        /// <summary>
        /// Test the property 'Licenses'
        /// </summary>
        [Fact]
        public void LicensesTest()
        {
            // TODO unit test for the property 'Licenses'
        }
    }
}
