/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UserExtension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UserExtensionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UserExtension
        //private IdentityApiUserV1UserExtension instance;

        public IdentityApiUserV1UserExtensionTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UserExtension
            //instance = new IdentityApiUserV1UserExtension();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UserExtension
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UserExtensionInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UserExtension
            //Assert.IsType<IdentityApiUserV1UserExtension>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
