/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UserPreferenceUpdatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UserPreferenceUpdatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UserPreferenceUpdatedResponse
        //private IdentityApiUserV1UserPreferenceUpdatedResponse instance;

        public IdentityApiUserV1UserPreferenceUpdatedResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UserPreferenceUpdatedResponse
            //instance = new IdentityApiUserV1UserPreferenceUpdatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UserPreferenceUpdatedResponse
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UserPreferenceUpdatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UserPreferenceUpdatedResponse
            //Assert.IsType<IdentityApiUserV1UserPreferenceUpdatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
