/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UserTenantProfilePaginatedItemsViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel
        //private IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel instance;

        public IdentityApiUserV1UserTenantProfilePaginatedItemsViewModelTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel
            //instance = new IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UserTenantProfilePaginatedItemsViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel
            //Assert.IsType<IdentityApiUserV1UserTenantProfilePaginatedItemsViewModel>(instance);
        }

        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
