/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1UserExtensionRemovedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1UserExtensionRemovedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1UserExtensionRemovedResponse
        //private IdentityApiUserV1UserExtensionRemovedResponse instance;

        public IdentityApiUserV1UserExtensionRemovedResponseTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1UserExtensionRemovedResponse
            //instance = new IdentityApiUserV1UserExtensionRemovedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1UserExtensionRemovedResponse
        /// </summary>
        [Fact]
        public void IdentityApiUserV1UserExtensionRemovedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1UserExtensionRemovedResponse
            //Assert.IsType<IdentityApiUserV1UserExtensionRemovedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
    }
}
