/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1SetUserExtensionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1SetUserExtensionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1SetUserExtensionRequest
        //private IdentityApiUserV1SetUserExtensionRequest instance;

        public IdentityApiUserV1SetUserExtensionRequestTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1SetUserExtensionRequest
            //instance = new IdentityApiUserV1SetUserExtensionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1SetUserExtensionRequest
        /// </summary>
        [Fact]
        public void IdentityApiUserV1SetUserExtensionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1SetUserExtensionRequest
            //Assert.IsType<IdentityApiUserV1SetUserExtensionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'DataType'
        /// </summary>
        [Fact]
        public void DataTypeTest()
        {
            // TODO unit test for the property 'DataType'
        }
    }
}
