/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityApiUserV1TenantStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityApiUserV1TenantStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityApiUserV1TenantStatus
        //private IdentityApiUserV1TenantStatus instance;

        public IdentityApiUserV1TenantStatusTests()
        {
            // TODO uncomment below to create an instance of IdentityApiUserV1TenantStatus
            //instance = new IdentityApiUserV1TenantStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityApiUserV1TenantStatus
        /// </summary>
        [Fact]
        public void IdentityApiUserV1TenantStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityApiUserV1TenantStatus
            //Assert.IsType<IdentityApiUserV1TenantStatus>(instance);
        }
    }
}
