/*
 * Me Api
 *
 * Me Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Me.Client.Model;
using EdGraph.Me.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Me.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TenantApiTenantV1SubscriptionListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantApiTenantV1SubscriptionListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TenantApiTenantV1SubscriptionListResponse
        //private TenantApiTenantV1SubscriptionListResponse instance;

        public TenantApiTenantV1SubscriptionListResponseTests()
        {
            // TODO uncomment below to create an instance of TenantApiTenantV1SubscriptionListResponse
            //instance = new TenantApiTenantV1SubscriptionListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TenantApiTenantV1SubscriptionListResponse
        /// </summary>
        [Fact]
        public void TenantApiTenantV1SubscriptionListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TenantApiTenantV1SubscriptionListResponse
            //Assert.IsType<TenantApiTenantV1SubscriptionListResponse>(instance);
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }
        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }
        /// <summary>
        /// Test the property 'StartDateTime'
        /// </summary>
        [Fact]
        public void StartDateTimeTest()
        {
            // TODO unit test for the property 'StartDateTime'
        }
        /// <summary>
        /// Test the property 'EndDateTime'
        /// </summary>
        [Fact]
        public void EndDateTimeTest()
        {
            // TODO unit test for the property 'EndDateTime'
        }
        /// <summary>
        /// Test the property 'ActualEndDateTime'
        /// </summary>
        [Fact]
        public void ActualEndDateTimeTest()
        {
            // TODO unit test for the property 'ActualEndDateTime'
        }
        /// <summary>
        /// Test the property 'GracePeriod'
        /// </summary>
        [Fact]
        public void GracePeriodTest()
        {
            // TODO unit test for the property 'GracePeriod'
        }
        /// <summary>
        /// Test the property 'NumberOfLicenses'
        /// </summary>
        [Fact]
        public void NumberOfLicensesTest()
        {
            // TODO unit test for the property 'NumberOfLicenses'
        }
        /// <summary>
        /// Test the property 'AssignedLicenses'
        /// </summary>
        [Fact]
        public void AssignedLicensesTest()
        {
            // TODO unit test for the property 'AssignedLicenses'
        }
        /// <summary>
        /// Test the property 'MaxAssignedLicenses'
        /// </summary>
        [Fact]
        public void MaxAssignedLicensesTest()
        {
            // TODO unit test for the property 'MaxAssignedLicenses'
        }
        /// <summary>
        /// Test the property 'LastMaxAssignedLicensesDateTime'
        /// </summary>
        [Fact]
        public void LastMaxAssignedLicensesDateTimeTest()
        {
            // TODO unit test for the property 'LastMaxAssignedLicensesDateTime'
        }
        /// <summary>
        /// Test the property 'LicenseType'
        /// </summary>
        [Fact]
        public void LicenseTypeTest()
        {
            // TODO unit test for the property 'LicenseType'
        }
        /// <summary>
        /// Test the property 'SubscriptionStatus'
        /// </summary>
        [Fact]
        public void SubscriptionStatusTest()
        {
            // TODO unit test for the property 'SubscriptionStatus'
        }
        /// <summary>
        /// Test the property 'AutoAssign'
        /// </summary>
        [Fact]
        public void AutoAssignTest()
        {
            // TODO unit test for the property 'AutoAssign'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Fact]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'LastModifiedBy'
        /// </summary>
        [Fact]
        public void LastModifiedByTest()
        {
            // TODO unit test for the property 'LastModifiedBy'
        }
        /// <summary>
        /// Test the property 'LastModifiedDateTime'
        /// </summary>
        [Fact]
        public void LastModifiedDateTimeTest()
        {
            // TODO unit test for the property 'LastModifiedDateTime'
        }

    }

}
